Really adding the new CIVL experiments material now.

diff --git a/experiments/civl/extra/Makefile b/experiments/civl/extra/Makefile
--- a/experiments/civl/extra/Makefile
+++ b/experiments/civl/extra/Makefile
@@ -1,67 +1,42 @@
-CIVL=civl
-VERIFY=$(CIVL) verify -ompNoSimplify -enablePrintf=false
+# This Makefile will run all CIVL "extra" experiments
+# Type "make foo" to verify foo.c only.
+# Type "make" to run all experiments.
+# CIVL's output is sent to a file (see variable OUT).
+# A summary of results is printed to stdout.
 
-all: sync1_no sync1_yes critsec3_no critsec3_yes atomic3_no atomic3_yes diffusion1_no diffusion1_yes diffusion2_no diffusion2_yes critsec2_no critsec2_yes prodcons_no prodcons_yes bar1_no bar1_yes bar2_no bar2_yes bar3_no bar3_yes 
+VERIFY= civl verify -errorBound=3
+OUT = civl_out.txt
+LOG = | tee -a $(OUT)
+CHECK_Y = $(LOG) | grep "Data-race detected"; \
+  if [ $$? -eq 0 ]; then echo "PASS"; else echo "FAIL"; fi
+CHECK_N = $(LOG) | grep "All properties .* hold"; \
+  if [ $$? -eq 0 ]; then echo "PASS"; else echo "FAIL"; fi
+ALL = sync1 critsec3 atomic3  diffusion1 diffusion2 critsec2 prodcons bar1 bar2 bar3
 
-sync1_no: sync1_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
+run: clean
+	$(MAKE) all
 
-sync1_yes: sync1_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
+all: $(ALL)
 
-critsec3_no: critsec3_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
+sync1 critsec2 critsec3 atomic3 bar1 bar2 bar3 : % : %_yes.c %_no.c
+	@echo "Checking $*_yes.c ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=2 $*_yes.c $(CHECK_Y)
+	@echo "Checking $*_no.c ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=2 $*_no.c $(CHECK_N)
 
-critsec3_yes: critsec3_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
+diffusion1 diffusion2 :  % : %_yes.c %_no.c
+	@echo "Checking $*_yes.c ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=5 $*_yes.c $(CHECK_Y)
+	@echo "Checking $*_no.c ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=5 $*_no.c $(CHECK_N)
 
-atomic3_no: atomic3_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-atomic3_yes: atomic3_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-bar1_no: bar1_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-bar1_yes: bar1_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-bar2_no: bar2_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-bar2_yes: bar2_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-bar3_no: bar3_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-bar3_yes: bar3_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-diffusion1_no: diffusion1_no.c
-	$(VERIFY) -input_omp_thread_max=5 $<
-
-diffusion1_yes: diffusion1_yes.c
-	$(VERIFY) -input_omp_thread_max=5 -errorBound=3 $<
-
-diffusion2_no: diffusion2_no.c
-	$(VERIFY) -input_omp_thread_max=5 $<
-
-diffusion2_yes: diffusion2_yes.c
-	$(VERIFY) -input_omp_thread_max=5 $<
-
-critsec2_no : critsec2_no.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-critsec2_yes : critsec2_yes.c
-	$(VERIFY) -input_omp_thread_max=2 $<
-
-prodcons_no  : prodcons_no.c
-	$(VERIFY) -input_omp_thread_max=8 $<
-
-prodcons_yes : prodcons_yes.c
-	$(VERIFY) -input_omp_thread_max=8 $<
+prodcons : % : %_yes.c %_no.c
+	@echo "Checking $*_yes.c ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=8 $*_yes.c $(CHECK_Y)
+	@echo "Checking $*_no.c ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=8 $*_no.c $(CHECK_N)
 
 clean:
-	rm -rf *~ CIVLREP OUT *.tmp 
+	rm -rf *~ CIVLREP $(OUT) *.tmp a.out
+
+.PHONY: $(ALL) all clean run
diff --git a/experiments/civl/micro-benchmarks/Makefile b/experiments/civl/micro-benchmarks/Makefile
--- a/experiments/civl/micro-benchmarks/Makefile
+++ b/experiments/civl/micro-benchmarks/Makefile
@@ -1,139 +1,154 @@
-CIVL=civl
-BOUND_VERIFY=$(CIVL) verify -ompNoSimplify -enablePrintf=false -input_omp_thread_max=5 -inputBOUND=10
-VERIFY=$(CIVL) verify -ompNoSimplify -input_omp_thread_max=5 -enablePrintf=false
-VERIFY2=$(CIVL) verify -ompNoSimplify -input_omp_thread_max=2 -enablePrintf=false
+# This Makefile will run all CIVL DataRaceBench experiments
+# Type "make foo" to verify foo.c only.
+# Type "make" to run all experiments.
+# CIVL's output is sent to a file (see variable OUT).
+# A summary of results is printed to stdout.
 
-all: all_yes all_no
+VERIFY = civl verify  # CIVL's verify command, assuming civl is in the PATH
+OUT = civl_out.txt   # CIVL output appended to this file
+LOG = | tee -a $(OUT)  # copy stdout to OUT file
+VERIFY5 = $(VERIFY) -input_omp_thread_max=5
+CHECK_Y = $(LOG) | grep "Data-race detected"; \
+  if [ $$? -eq 0 ]; then echo "PASS"; else echo "FAIL"; fi
+CHECK_N = $(LOG) | grep "All properties .* hold"; \
+  if [ $$? -eq 0 ]; then echo "PASS"; else echo "FAIL"; fi
 
-all_yes: $(patsubst  %.c, C_%, $(wildcard *yes.c))
+# This group takes 1..5 threads (and no parameters)
+GROUP1 = DRB023-sections1-orig-yes \
+DRB051-getthreadnum-orig-no \
+DRB059-lastprivate-orig-no \
+DRB069-sectionslock1-orig-no \
+DRB075-getthreadnum-orig-yes \
+DRB076-flush-orig-no \
+DRB077-single-orig-no \
+DRB088-dynamic-storage-orig-yes \
+DRB089-dynamic-storage2-orig-yes \
+DRB074-flush-orig-yes \
+DRB103-master-orig-no \
+DRB108-atomic-orig-no \
+DRB120-barrier-orig-no \
+DRB121-reduction-orig-no \
+DRB124-master-orig-yes \
+DRB125-single-orig-no \
+DRB126-firstprivatesections-orig-no \
+DRB139-worksharingcritical-orig-no \
+DRB140-reduction-barrier-orig-yes \
+DRB141-reduction-barrier-orig-no \
+DRB172-critical2-orig-no
 
-all_no: $(patsubst  %.c, C_%, $(wildcard *no.c))
+GROUP1_Y = $(filter %yes,$(GROUP1))
+GROUP1_N = $(filter %no,$(GROUP1))
 
-C_%: %.c
-	$(BOUND_VERIFY) $<
+# This group takes 1..5 threads and BOUND=10
+GROUP2 = DRB001-antidep1-orig-yes \
+DRB002-antidep1-var-yes \
+DRB003-antidep2-orig-yes \
+DRB004-antidep2-var-yes \
+DRB011-minusminus-orig-yes \
+DRB012-minusminus-var-yes \
+DRB013-nowait-orig-yes \
+DRB014-outofbounds-orig-yes \
+DRB015-outofbounds-var-yes \
+DRB018-plusplus-orig-yes \
+DRB019-plusplus-var-yes \
+DRB020-privatemissing-var-yes \
+DRB021-reductionmissing-orig-yes \
+DRB022-reductionmissing-var-yes \
+DRB028-privatemissing-orig-yes \
+DRB029-truedep1-orig-yes \
+DRB030-truedep1-var-yes \
+DRB031-truedepfirstdimension-orig-yes \
+DRB032-truedepfirstdimension-var-yes \
+DRB033-truedeplinear-orig-yes \
+DRB034-truedeplinear-var-yes \
+DRB037-truedepseconddimension-orig-yes \
+DRB038-truedepseconddimension-var-yes \
+DRB041-3mm-parallel-no \
+DRB047-doallchar-orig-no \
+DRB048-firstprivate-orig-no \
+DRB050-functionparameter-orig-no \
+DRB052-indirectaccesssharebase-orig-no \
+DRB053-inneronly1-orig-no \
+DRB054-inneronly2-orig-no \
+DRB057-jacobiinitialize-orig-no \
+DRB060-matrixmultiply-orig-no \
+DRB061-matrixvector1-orig-no \
+DRB063-outeronly1-orig-no \
+DRB064-outeronly2-orig-no \
+DRB065-pireduction-orig-no \
+DRB066-pointernoaliasing-orig-no \
+DRB067-restrictpointer1-orig-no \
+DRB068-restrictpointer2-orig-no \
+DRB090-static-local-orig-yes \
+DRB093-doall2-collapse-orig-no \
+DRB104-nowait-barrier-orig-no \
+DRB110-ordered-orig-no \
+DRB111-linearmissing-orig-yes \
+DRB113-default-orig-no \
+DRB169-missingsyncwrite-orig-yes \
+DRB170-nestedloops-orig-no \
+DRB005-indirectaccess1-orig-yes \
+DRB006-indirectaccess2-orig-yes \
+DRB007-indirectaccess3-orig-yes \
+DRB008-indirectaccess4-orig-yes \
+DRB009-lastprivatemissing-orig-yes \
+DRB010-lastprivatemissing-var-yes \
+DRB016-outputdep-orig-yes \
+DRB017-outputdep-var-yes \
+DRB035-truedepscalar-orig-yes \
+DRB036-truedepscalar-var-yes \
+DRB039-truedepsingleelement-orig-yes \
+DRB040-truedepsingleelement-var-yes \
+DRB045-doall1-orig-no \
+DRB046-doall2-orig-no \
+DRB055-jacobi2d-parallel-no \
+DRB073-doall2-orig-yes \
+DRB109-orderedmissing-orig-yes
 
-C_DRB005-indirectaccess1-orig-yes:: DRB005-indirectaccess1-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+GROUP2_Y = $(filter %yes,$(GROUP2))
+GROUP2_N = $(filter %no,$(GROUP2))
 
-C_DRB006-indirectaccess2-orig-yes:: DRB006-indirectaccess2-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+# Misc. group: a few special cases
+MISC = DRB043-adi-parallel-no \
+DRB058-jacobikernel-orig-no \
+DRB062-matrixvector2-orig-no
 
-C_DRB007-indirectaccess3-orig-yes:: DRB007-indirectaccess3-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+ALL = $(GROUP1) $(GROUP2) $(MISC)
 
-C_DRB008-indirectaccess4-orig-yes:: DRB008-indirectaccess4-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+run: clean
+	$(MAKE) all
 
-C_DRB009-lastprivatemissing-orig-yes:: DRB009-lastprivatemissing-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+all: $(ALL)
 
-C_DRB010-lastprivatemissing-var-yes:: DRB010-lastprivatemissing-var-yes.c
-	$(VERIFY) -inputN=10 $<
+$(GROUP1_Y) : % : %.c
+	@echo "Checking $@ with nthreads<=5 ..." $(LOG)
+	@$(VERIFY5) $< $(CHECK_Y)
 
-C_DRB016-outputdep-orig-yes:: DRB016-outputdep-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+$(GROUP1_N) : % : %.c
+	@echo "Checking $@ with nthreads<=5 ..." $(LOG)
+	@$(VERIFY5) $< $(CHECK_N)
 
-C_DRB017-outputdep-var-yes:: DRB017-outputdep-var-yes.c
-	$(VERIFY) -inputN=10 $<
+$(GROUP2_Y) : % : %.c
+	@echo "Checking $@ with nthreads<=5, BOUND=10 ..." $(LOG)
+	@$(VERIFY5) -inputBOUND=10  $< $(CHECK_Y)
 
-C_DRB023-sections1-orig-yes::  DRB023-sections1-orig-yes.c
-	$(VERIFY) $<
+$(GROUP2_N) : % : %.c
+	@echo "Checking $@ with nthreads<=5, BOUND=10 ..." $(LOG)
+	@$(VERIFY5) -inputBOUND=10  $< $(CHECK_N)
 
-C_DRB035-truedepscalar-orig-yes:: DRB035-truedepscalar-orig-yes.c
-	$(VERIFY) -inputN=10 $<
+DRB043-adi-parallel-no: DRB043-adi-parallel-no.c
+	@echo "Checking $@ with nthreads<=5, BOUND=4 ..." $(LOG)
+	@$(VERIFY5) -inputBOUND=4 $< $(CHECK_N)
 
-C_DRB036-truedepscalar-var-yes:: DRB036-truedepscalar-var-yes.c
-	$(VERIFY) -inputN=10 $<
+DRB058-jacobikernel-orig-no: DRB058-jacobikernel-orig-no.c
+	@echo "Checking $@ with nthreads<=5, MSIZE_B=5, NITER_B=5 ..." $(LOG)
+	@$(VERIFY5) -inputMSIZE_B=5 -inputNITER_B=5 $< $(CHECK_N)
 
-C_DRB039-truedepsingleelement-orig-yes:: DRB039-truedepsingleelement-orig-yes.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB040-truedepsingleelement-var-yes:: DRB040-truedepsingleelement-var-yes.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB041-3mm-parallel-no:: DRB041-3mm-parallel-no.c
-	$(VERIFY2) -inputN=10 $<
-
-C_DRB043-adi-parallel-no:: DRB043-adi-parallel-no.c
-	$(VERIFY2) -inputN=4 $<
-
-C_DRB045-doall1-orig-no:: DRB045-doall1-orig-no.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB046-doall2-orig-no:: DRB046-doall2-orig-no.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB051-getthreadnum-orig-no:: DRB051-getthreadnum-orig-no.c
-	$(VERIFY) $<
-
-C_DRB055-jacobi2d-parallel-no:: DRB055-jacobi2d-parallel-no.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB058-jacobikernel-orig-no:: DRB058-jacobikernel-orig-no.c
-	$(VERIFY) -inputBOUND=5 $<
-
-C_DRB059-lastprivate-orig-no::  DRB059-lastprivate-orig-no.c
-	$(VERIFY) $<
-
-C_DRB060-matrixmultiply-orig-no:: DRB060-matrixmultiply-orig-no.c
-	$(VERIFY) $<
-
-C_DRB062-matrixvector2-orig-no:: DRB062-matrixvector2-orig-no.c
-	$(VERIFY2) -inputBOUND=10 $<
-
-C_DRB069-sectionslock1-orig-no:: DRB069-sectionslock1-orig-no.c
-	$(VERIFY2) $<
-
-C_DRB073-doall2-orig-yes:: DRB073-doall2-orig-yes.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB075-getthreadnum-orig-yes:: DRB075-getthreadnum-orig-yes.c
-	$(VERIFY) $<
-
-C_DRB076-flush-orig-no:: DRB076-flush-orig-no.c
-	$(VERIFY2) $<
-
-C_DRB077-single-orig-no:: DRB077-single-orig-no.c
-	$(VERIFY) $<
-
-C_DRB088-dynamic-storage-orig-yes:: DRB088-dynamic-storage-orig-yes.c
-	$(VERIFY) $<
-
-C_DRB089-dynamic-storage2-orig-yes:: DRB089-dynamic-storage2-orig-yes.c
-	$(VERIFY) $<
-
-C_DRB103-master-orig-no:: DRB103-master-orig-no.c
-	$(VERIFY) $<
-
-C_DRB108-atomic-orig-no:: DRB108-atomic-orig-no.c
-	$(VERIFY) $<
-
-C_DRB109-orderedmissing-orig-yes:: DRB109-orderedmissing-orig-yes.c
-	$(VERIFY) -inputN=10 $<
-
-C_DRB120-barrier-orig-no:: DRB120-barrier-orig-no.c
-	$(VERIFY) $<
-
-C_DRB121-reduction-orig-no:: DRB121-reduction-orig-no.c
-	$(VERIFY) $<
-
-C_DRB124-master-orig-yes:: DRB124-master-orig-yes.c
-	$(VERIFY) $<
-
-C_DRB125-single-orig-no:: DRB125-single-orig-no.c
-	$(VERIFY) $<
-
-C_DRB126-firstprivatesections-orig-no:: DRB126-firstprivatesections-orig-no.c
-	$(VERIFY2) $<
-
-C_DRB139-worksharingcritical-orig-no:: DRB139-worksharingcritical-orig-no.c
-	$(VERIFY) $<
-
-C_DRB141-reduction-barrier-orig-no:: DRB141-reduction-barrier-orig-no.c
-	$(VERIFY2) $<
-
-C_DRB172-critical2-orig-no:: DRB172-critical2-orig-no.c
-	$(VERIFY) $<
+DRB062-matrixvector2-orig-no: DRB062-matrixvector2-orig-no.c
+	@echo "Checking $@ with nthreads<=4, BOUND=5 ..." $(LOG)
+	@$(VERIFY) -input_omp_thread_max=4 -inputBOUND=5 $< $(CHECK_N)
 
 clean:
-	rm -rf CIVLREP *~
+	rm -rf *~ *.tmp a.out $(OUT) CIVLREP
+
+.PHONY: all clean $(ALL) run
